poc3 blog initial commit
ethersphere/swarm-docs pull request #9
Opened 2018-06-20 11:42 UTC by zelig

2018-06-20 11:44 UTC, janos commented on blog/poc3.md
> +POC 3 is running now on the public Testnet. The foundation is running a 50-node strong cluster with a public gateway on http://swarm-gateways.net. This is fast growing as our collaborators switch on
https://swarm-gateways.net with _https_

2018-06-20 12:27 UTC, janos commented on blog/poc3.md
> +Swarm is a peer-to-peer network of nodes running the swarm client. The network uses ethereum's devp2p/rlpx networking layer to run the bzz suite of protocols. nodes are identified with a swarm addres
Capital N: "Nodes are identified..."

2018-06-20 12:27 UTC, janos commented on blog/poc3.md
> +The Swarm network implements a :dfn:`distributed preimage archive`, which is essentially a specific type of content addressed distributed chunk store;
Maybe to add ", or DPA" after :dfn:`distributed preimage archive` as acronym is used later in text.

2018-06-20 12:27 UTC, janos commented on blog/poc3.md
> +The Swarm content service offers an HTTP interface via a local proxy running on your local machine and connected to the rest of the swarm. This proxy used in the browser to serve static assets (such
To link "six url schemes" to a documentation that lists them?

2018-06-20 12:27 UTC, janos commented on blog/poc3.md
> +`pss` is a  pss is the sound of swarm whispered as it were, since it combines swarm (bzz) routing with whisper (shh) envelopes and topics (`bzz`+`shh`=`pss`) defining a messaging protocol with strong
Remove "is a  pss".

2018-06-20 12:27 UTC, janos commented on blog/poc3.md
> +Swarm POC3 supports encryption so protecting your private data has never been easier. Once Access Control Trees are implemented, we will have a fully fledged solution for 'sharing' a subdirectory, a
"drop box" -> Dropbox
"google drive" -> Google Drive

2018-06-20 12:27 UTC, janos commented on blog/poc3.md
> +Just as the past year, these coming 10+ month will be very very exciting and challed. We are on target delivering Swarm POC4 (production beta prerelease) in the first half of 2019.
challed?

2018-06-20 12:27 UTC, janos commented on blog/poc3.md
> +After rounding up [the swap swear and swindle framework for decentralised service economies]() (see the [3rd orange paper]() and a [talk]() and the [implementation]()), we apply it to the storage ins
Missing links in this line, but I assume that they will be added later.

2018-06-20 14:43 UTC, janos approved these changes
Thanks Viktor. 👍

2018-06-20 16:59 UTC, acud requested changes
please run a search and replace all
swarm
with
Swarm
:)

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +POC 3 is running now on the public Testnet. The foundation is running a 50-node strong cluster with a public gateway on https://swarm-gateways.net. This is fast growing as our collaborators switch on
public testnet

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +POC 3 is running now on the public Testnet. The foundation is running a 50-node strong cluster with a public gateway on https://swarm-gateways.net. This is fast growing as our collaborators switch on
This number is fast growing

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Swarm is a service offers APIs to upload and download content and through a url-based addressing offers virtual hosting of web-sites and dapps without webservers, using a peer-to-peer distributed inf
is a service that offers

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Swarm is a service offers APIs to upload and download content and through a url-based addressing offers virtual hosting of web-sites and dapps without webservers, using a peer-to-peer distributed inf
addressing that offers

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +The references of data chunks are themselves packaged into a chunk which in turn has its own hash. In this way the content gets mapped into a merkle tree the root hash of which, called the Swarm hash
offers integrity protected random access for large files

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +The references of data chunks are themselves packaged into a chunk which in turn has its own hash. In this way the content gets mapped into a merkle tree the root hash of which, called the Swarm hash
the thing one does when skipping parts

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +The Swarm network implements a :dfn:`distributed preimage archive` (DPA), which is essentially a specific type of content addressed distributed chunk store;
are you going to deploy this on RTD? the links above are in MD format but this is RST

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +node(s) closest to the address of a chunk do not only serve information about the content but actually host the data. This DPA is the underlying distributed component of the Swarm service. When you u
a process called "syncing"

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +The viability of routing hinges on the assumption that any node (uploader/requester) can 'reach' any other node (storer). This can be solved by maintaining a specific :dfn:`network topology`, i.e., c
same question regarding RST

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +The viability of routing hinges on the assumption that any node (uploader/requester) can 'reach' any other node (storer). This can be solved by maintaining a specific :dfn:`network topology`, i.e., c
what is logarithmic to network size? missing the other part of the sentence

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +As retrieve requests are relayed towards the nodes close to the chunk address, the first peer that stores the requested chunk will send the chunk data back to the requesting peer. As the delivery is
relayed towards the nodes closer to

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +As retrieve requests are relayed towards the nodes close to the chunk address, the first peer that stores the requested chunk will send the chunk data back to the requesting peer. As the delivery is
service-for-service

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +As retrieve requests are relayed towards the nodes close to the chunk address, the first peer that stores the requested chunk will send the chunk data back to the requesting peer. As the delivery is
swarm accounting protocol (SWAP)

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +A manifest is a data structure describing file collections; they specify paths and corresponding content hashes allowing for URL based content retrieval. The `bzz` url scheme assumes that the content
3.0

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Manifests can also be mapped to a filesystem directory tree, which allows for uploading and downloading directories. Finally, manifests can also be considered indexes, so it can be used to implement
of directories

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Manifests can also be mapped to a filesystem directory tree, which allows for uploading and downloading directories. Finally, manifests can also be considered indexes, so it can be used to implement
so it can be used to => which, in turn, allows to

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +In sum, the overall vision of swarm offers a fully decentralised peer-to-peer internet which is not only fault-tolerant, has zero downtime and censorship rexistance but also economically self-sustain
censorship rexistance => censorship resistant

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +In sum, the overall vision of swarm offers a fully decentralised peer-to-peer internet which is not only fault-tolerant, has zero downtime and censorship rexistance but also economically self-sustain
which, by compensating nodes for contributing their bandwidth and disk space, achieves

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +In sum, the overall vision of swarm offers a fully decentralised peer-to-peer internet which is not only fault-tolerant, has zero downtime and censorship rexistance but also economically self-sustain
the one hand and guarantees persistance of important yet rarely accessed data like archives or backups
||
\\/
the one hand and guarantees persistence of important yet rarely accessed data like archives or backups on the other hand.

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +* search (like google, not discussed here)
lets get rid of google
~~(like google, not discussed here)~~

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +* resource-intensive computation (truebit, golem, not discussed here)
~~not discussed here~~

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +## PSS
PSS (Postal Services over Swarm)

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +This messaging infrastrucure can be the foundation of a whole new system of internode communication services (the email, tweet, newsletter of the future). From this systemic perspective PSS is Postal
~~From this systemic perspective PSS is Postal Services over Swarm~~

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +With `pss` you can send messages to any node in the swarm network.
can send and receive messages from

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Using partial addressing, pss offers a sliding scale of recipient anonymity: the larger the destination neighbourhood (the smaller prefix you reveal of the intended recipient overlay address), the mo
exact duplicate of the previous paragraph

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Nodes can communicate privately with each other  even if they are not each others' peers.
remove one space before `even`

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +As a result PSS can maintain arbitrary dark subnetworks in swarm. These subnetworks indentified by the topics can even handle devp2p protocols.
sub-networks

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +As a result PSS can maintain arbitrary dark subnetworks in swarm. These subnetworks indentified by the topics can even handle devp2p protocols.
indentified => identified

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Not only can pss be used for slow-scale chat messaging, but also for secure file transfer, notifications and collaborative protocols like [CRASH proof of custody]() used in storage incentivisation.
(link missing?)

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> + communications tool ([Onyx](https://blog.mainframe.com/mainframe-pre-alpha-release-fca532317111)) and their web3 SDK, and [Status](http://status.im) have expressed interest in building it into their
communications tool,

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Since hashes can be assumed to be collision free, they are bound to one specific version of a content. Hash addressing is therefore immutable in the strong sense that you cannot even express mutable
sense that: ~~that you cannot even express mutable content~~

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Users of the web, however, are accustomed to mutable resources, looking up domains and expect to see the most up to date version of the 'site'. Mutable resources are made possible by the ethereum nam
Ethereum Name Service

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Here is how it works: a publisher creates a mutable resource at time `t` for the name "my daily tweets", that she intends to update every day once (note this in itself not a promise). By hashing toge
not sure if i'd go into such technical detail within the scope of this blog post

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +A publisher creates new version of a mutable resource by serialising `(name, start, period, version)` and signing it.
see above

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +## Drop box
FUSE support

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +Due to the fact that swarm retrieval is on-demand, Swarm FUSE mounts are readable with no latency. Swarm FUSE supports file system write operations (creating, appending, updating files) by maintainin
the collection's

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +As still part of the POC3 series, we are planning to switch on a revamped SWAP accounting for chunk deliveries.
~~still~~

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +The first few releases will also address some technical debt accumulated as well as optimisations of retrieval and syncing.
accumulated as part of the network rewrite

2018-06-20 16:59 UTC, justelad commented on blog/poc3.md
> +We keep on building a community with our allies who champion the values of web3 and actively collaborate through working groups building the foundational infrastructure, the backbone of second layer
3.0

2018-06-20 18:15 UTC, holisticode requested changes
A couple of typos. There are a couple of sentences I would try to write shorter.

I made some suggestions for expressions/sentences which sounded strange to me. It's up to you if you want to accept those suggestions or not.

Consider adding images as it is a blog post

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Swarm content storage is easiest described to not-so-technical audience as "bittorrent on steroids". Here we venture into a more elaborate technical presentation.
described to a .... audience....

Instead of "not-so-technical", maybe "general" audience? Less discriminating :)

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Swarm is a service offers APIs to upload and download content and through a url-based addressing offers virtual hosting of web-sites and dapps without webservers, using a peer-to-peer distributed inf
offers repeated. I suggest:

Swarm is a service offering APIs to upload and download content. Through a URL-based addressing it allows for virtual hosting of web-sites and dapps without the need for webservers, using a peer-to-peer distributed infrastructure.

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +The references of data chunks are themselves packaged into a chunk which in turn has its own hash. In this way the content gets mapped into a merkle tree the root hash of which, called the Swarm hash
add few commas: ...gets mapped into a merkle tree, whose root hash, called the Swarm hash, is used as a reference to a file.

This hierarchical merklised swarm hash construct offers integrity protected random access into large file, permitting things like skipping parts of a video or look up a key in a database file.

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Swarm is a peer-to-peer network of nodes running the swarm client. The network uses ethereum's devp2p/rlpx networking layer to run the bzz suite of protocols. Nodes are identified with a swarm addres
Do you like to use "swarm client" here? Being p2p, I'd rather prefer to not see terms like server and client; what about "running the swarm binary".

Nodes are identified with a swarm address deterministically derived from the node's ethereum account public key. This swarm address of a node shares the address space of the chunks themselves. Thus, we can derive the proximity in this address space between nodes and chunks.

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +The Swarm network implements a :dfn:`distributed preimage archive` (DPA), which is essentially a specific type of content addressed distributed chunk store;
a specific type of a content addressed distributed chunk store. Nodes closest.... (make short sentences)

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +node(s) closest to the address of a chunk do not only serve information about the content but actually host the data. This DPA is the underlying distributed component of the Swarm service. When you u
...the chunks need to reach the nodes that are closest to it **for storage** (**a process we** called syncing)**. W**hen you retrieve chunks, **nodes send requests which are relayed** towards the chunk's address via ever closer peers.

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +node(s) closest to the address of a chunk do not only serve information about the content but actually host the data. This DPA is the underlying distributed component of the Swarm service. When you u
We should add something explaining that "closer" isn't geographical. Something like

Proximity (being far or close) in the address space is not defined by a geographical location, but by a binary logical distance function.

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Since for delivery, each node needs to know only the immediate peer upstream, there is no need to know who originated the request. As a consequence forwarding kademlia allows for "anonymous private b
When a node delivers a chunk, it only needs to know the immediate peer upstream - there is no need to know at which node the request originated.

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +The Swarm content service offers an HTTP interface via a local proxy running on your local machine and connected to the rest of the swarm. This proxy used in the browser to serve static assets (such
Why "local proxy" and not simply "local node"?

The Swarm content delivery service offers a HTTP interface on the local node running on your machine which is connected to the rest of the swarm. It can serve static (such as HTML or images) as well as dynamic assets (like Javascript) for decentralised applications to standard compliant web browsers. This HTTP interface can be queried via six URL schemes that dapps can use to interact with the Swarm content storage API.

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +A manifest is a data structure describing file collections; they specify paths and corresponding content hashes allowing for URL based content retrieval. The `bzz` url scheme assumes that the content
Does a manifest really describe file collections? It could also describe a single file. I suggest "...describing resources and resource collections".

The `bzz` **URL`` scheme...in the domain ``part of the URL`` is....

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +In sum, the overall vision of swarm offers a fully decentralised peer-to-peer internet which is not only fault-tolerant, has zero downtime and censorship rexistance but also economically self-sustain
...overall vision of **S**warm **portrays** a fully decentralised... (just to not use "offers" again, whatever you prefer)

typo re**x**istance

built-in incentive system. By compensating nodes for contributing....and disk space, Swarm achieves smooth low-latency scalable retrieval of popular content while guaranteeing persist**e**nce of imporant yet rarely...

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +The ambitious vision of a truely decentralised internet implies the existence of base-layer infrastructure for all the things that allows you to run auto-scalable real-time interactive web applicatio
typo: truly 

for all the things that allow you (not allows)

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +* hosting (swarm)
**S**warm

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +As we continue finding solutions to these ingredients, swarm shows remarkable signs of good design as various solutions simply fall out of it often much to our surprise.
**S**warm

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +As we continue finding solutions to these ingredients, swarm shows remarkable signs of good design as various solutions simply fall out of it often much to our surprise.
...simply fall out of **it**  --- fall out of what? This sentence sounds strange

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +In what follows we give an overview of new features in swarm that are available
**S**warm

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Instead of chunk hash reference, pss messages specify a destination in the overlay address space independently of the message payload. This destination can describe a specific node if it is a complet
The destination can be set for a specific node if specified as a complete overlay address or for a neighborhood if only partially specified. The message is relayed through devp2p peer connections using forwarding kademlia until arriving at destination (passing messages via semi-permanent peer-to-peer TCP connections between relaying nodes using kademlia routing).

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Using partial addressing, pss offers a sliding scale of recipient anonymity: the larger the destination neighbourhood (the smaller prefix you reveal of the intended recipient overlay address), the mo
This seems to repeat the previous paragraph. Remove or edit/merge

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +As a result PSS can maintain arbitrary dark subnetworks in swarm. These subnetworks indentified by the topics can even handle devp2p protocols.
**S**warm (not going to point to this anymore)

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Here is how it works: a publisher creates a mutable resource at time `t` for the name "my daily tweets", that she intends to update every day once (note this in itself not a promise). By hashing toge
note this in itself **is** not a promise

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +A publisher creates new version of a mutable resource by serialising `(name, start, period, version)` and signing it.
creates **a** new version

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +We mentioned that thanks to manifests, directory trees and collections represented by manifests can be mapped uniquely. This does not only allow upload and download into directory but also use FUSE i
I suggest ...directory trees and collections (represented by manifests) can be mapped uniquely (brackets for better readabilty)

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +Both [FUSE](http://swarm-guide.readthedocs.io/en/usage.html#FUSE) and [encryption](http://swarm-guide.readthedocs.io/en/usage.html#Encryption) are fully functional in POC3.
We should mention that FUSE is not available on Windows

2018-06-20 18:15 UTC, holisticode commented on blog/poc3.md
> +We are implementing two layers of erasure coding for redundancy, one is primarily against dropout and network switch issues to guarantee low latency retrieval. Another one is part of the two tiered i
Another one is part of the two tiered insurance system. **S**takeless farmers get positive rewards for proof of custody. Staked insurers continually perform scan-and-repair on highly redundant **stored** **(coded sounded strange to me here).** chunks. Punitive measures may be taken as well as compensatory insurance fees levied against storers if integrity of insured content is compromised.

2018-06-21 11:18 UTC, gbalint reviewed
Generally I think this is very heavy text, with not enough examples and no illustrations at all. E.g. for the merkle tree at the beginning we should definitely have a drawing. Maybe @holisticode already made one for the docs?

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +A [*manifest*](http://swarm-guide.readthedocs.io/en/latest/usage.html#Manifests) is a data structure describing file collections; they specify paths and corresponding content hashes allowing for URL-
IMHO urls schemes are too much information here. I would just write that there is an http api for dapps to interact with Swarm content storage. The 6 schemes are not so important details

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +This latter feature is a main differentiator of the project and allows us to trial very complex emergent properties of a network of nodes, test algorithmic correctness, fault tolerance and scalabilit
Let's start a new paragraph with the sentence "POC3 code was....",and the first sentence about the simulation can go to the previous paragraph.

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +## PSS
For these features I would link the corresponding summit presentation videos

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +the larger the destination neighbourhood (the smaller prefix you reveal of the intended recipient overlay address), the more difficult it is to identify the real recipient. As recipient anonymity inc
Example would really help here, with different kind of recipients

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +## Mutability
Again, let's link the summit video

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +Combining FUSE with MRU, on each change we can issue a mutable resource update, this makes it possible to think of FUSE to sync your entire home folder between devices, virtually serving as the backe
Dropbox is one word, and I would use the term "Dropbox-like functionality",  because dropbox is an actual company/brand/product

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +Swarm POC3 supports [*encryption*](http://swarm-guide.readthedocs.io/en/latest/usage.html#Encryption) so protecting your private data has never been easier. Once *Access Control Trees* are implemente
Access Control Trees are not described, so it is not really understandable why they are a solution.

2018-06-21 11:18 UTC, gbalint commented on blog/poc3.md
> +The first few releases will also address some technical debt accumulated as part of the network rewrite as well as optimisations of retrieval and syncing.
IMHO talking about technical debt is too much detail about the project

2018-06-21 13:27 UTC, cobordism requested changes
more comments in ethersphere HQ gitter channel

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +Two [Swarm summits](https://swarm-gateways.net/bzz:/swarm-summit.eth), two [orange papers](http://swarm-guide.readthedocs.io/en/latest/resources.html#orange-papers) and [forty thousand lines of code]
swarm-orange-summit.eth

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +Swarm is a service that provides APIs to upload and download content and through a url-based addressing offers *virtual hosting of websites* and decentralised applications (dapps) without webservers,
through a url-based --> through url-based

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +As retrieve requests are relayed towards the nodes close to the chunk address, the first peer that stores the requested chunk will send the chunk data back to the requesting peer. As the delivery is
The *Swarm accounting protocol* (to be implemented in POC 3.1)  allows for

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +Since for delivery, each node needs to know only the immediate peer upstream, there is no need to know who originated the request. As a consequence forwarding kademlia allows for "anonymous private b
delete the "as it were".

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +In the past year [the Swarm team](https://pbs.twimg.com/media/DetPkqZX0AAAsPp.jpg:large) has grown in size and now on fire delivering the vision. We have been busy redesigning the network layer, rewr
has grown in size and _IS_ now on fire

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +This latter feature is a main differentiator of the project and allows us to trial very complex emergent properties of a network of nodes, test algorithmic correctness, fault tolerance and scalabilit
finalised just for the -> finalised just in time for the

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +* resource-intensive computation (Truebit, Golem, not discussed here)
why is this (list) here at all? What does this have to do with the 0.3 release?

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +Here is how it works: a publisher creates a mutable resource at time `t` for the name "my daily tweets", that she intends to update every day once (note this in itself is not a promise). By hashing t
every day once -> once per day

2018-06-21 13:27 UTC, cobordism commented on blog/poc3.md
> +This simple system is surprisingly powerful and is envisioned to be at the core of implementing group chat, shared FUSE state, and [poor man's consensus](https://www.sharelatex.com/1452913241cqmzrpfp
that sharelatex link requires a login. it has no place in a blog post.

2018-06-21 13:45 UTC, gbalint commented on blog/poc3.md
> +This simple system is surprisingly powerful and is envisioned to be at the core of implementing group chat, shared FUSE state, and [poor man's consensus](https://www.sharelatex.com/1452913241cqmzrpfp
Maybe the pdf could be uploaded to swarm and link that? :)

2019-07-11 06:43 UTC, closed without merging